version: "3.9"

# Adapted to run with an external DB
services:
  app:
    image: monica:apache
    environment:
      - APP_ENV=production
      - LOG_CHANNEL=stderr
      - CACHE_DRIVER=database
      - SESSION_DRIVER=database
      - QUEUE_DRIVER=sync
    volumes:
      - data:/var/www/html/storage
    restart: unless-stopped
    
volumes:
  data:
    name: data
